### ISSUE TITLE
Готов сдать все программы из turtle.my

### ISSUE THREAD

**Issue by MaKYaro** [MaKYaro/prog_Klykin#4]
@antosha417 Посмотри, пожалуйста, turtle. Большинство программ в том же порядке, что и в задании

**Comment by antosha417** [comment]
Добавь хеш коммита к своему комментарию, я просил в телеграмме об этом, спасибо.

**Comment by MaKYaro** [comment]
@antosha417 , эти программы из turtle.my: turtle1.py, turtle2.py, turtle3.py, turtle4.py, turtle5.py, turtle6.py, turtle7.py, turtle8.py, turtle9.py, turtle10.py, turtle11.py, turtle12.py, turtle13.py, turtle14.py.

**Comment by antosha417** [comment]
Супер, в каком файле фракталы у тебя?

**Comment by antosha417** [comment]
Пайчарм ругается на твой кодстайл и несоблюдение пеп8, поправь, пожалуйста.

**Comment by antosha417** [comment]
Пока ставлю тебе 0.7  за задачу, чтобы поднять поправь код.

**Comment by MaKYaro** [comment]
@antosha417 Исправил то, что выделял PyCharm
 4cb2ed303fac659ff7e65fe1ca9db1f52be63bee

**Comment by antosha417** [comment]
> Супер, в каком файле фракталы у тебя?

**Comment by MaKYaro** [comment]
antosha417, фракталы в turtle10.py, turtle11.py, turtle12.py, turtle13.py, turtle14.py

**Comment by antosha417** [comment]
Не запускал код. Ты списывал?

**Comment by antosha417** [comment]
Если хочешь баллы за эту задачу подойди ко мне перед семинаром. (Это значит тебе нужно по-раньше подойти)

**Comment by antosha417** [comment]
Поговорили, сделай как я просил и закрывай issue.

**Comment by antosha417** [comment]
Не вижу где сделал как я просил.
