### ISSUE TITLE
Готов сдать программы из robot.my

### ISSUE THREAD

**Issue by MaKYaro** [MaKYaro/prog_Klykin#5]
@antosha417 Посмотри, пожалуйста. Все программы в том же порядке, что и в задании.

**Comment by antosha417** [comment]
Добавь хеш коммита к своему комментарию, я просил в телеграмме об этом, спасибо.

**Comment by MaKYaro** [comment]
@antosha417, вот эти задания из robot.my:
task1.py,
task2.py,
task3.py,
task4.py,
task5.py,
task6.py,
task7.py.

**Comment by antosha417** [comment]
Поправь 6 и 7, там, видимо , мердж неудачно прошёл. Почитай про git merge в интернетах. Закрывай issue
