### ISSUE TITLE
Готов сдать задания из picture.my

### ISSUE THREAD

**Issue by MaKYaro** [MaKYaro/prog_Klykin#6]
@antosha417, посмотри, пожалуйста задания из picture.my
 dfdbbe8f101c35d4270eaa73b00b3fa8f3d3f30c

**Comment by antosha417** [comment]
`window.close()` забыл в конце. 
Везде где у тебя к названиям переменных прилеплены цифры нужно переписать через циклы.

**Comment by antosha417** [comment]
ты можешь делать цикл по массиву точек, например:
```python
for line_coords in ((0, 0), (1, 1)), \
                   ((2, 3), (5, 10)), \
                   ((100500, 3), (5, 10)):
    do_something(line_coords)
    
```

**Comment by antosha417** [comment]
Пока ставлю тебе  0,6 за задачу, чтобы поднять поправь код.

**Comment by MaKYaro** [comment]
@antosha417, исправил код
9e1f8b58f614f103325d8f50435e369041d00204

**Comment by antosha417** [comment]
* Программа не запускается. 
* Непонятные цифры в названиях функций. 
* Видимо, не знаешь пройти циклом `for` по массиву. 
* Опять копипаста: `gr.Point` лучше написать 1 раз в цикле, а не 1000 раз когда задаёшь точки.
* Убери границы у облаков, так не очень красиво.

**Comment by MaKYaro** [comment]
@antosha417, исправил код 75af17eb6adaa6387be15b26cb9caa92b7972d88

**Comment by antosha417** [comment]
Удалил одну строчку?
![latest-screenshot](https://user-images.githubusercontent.com/14187674/49570714-76268e80-f948-11e8-99c9-8d2faf897e49.png)

**Comment by antosha417** [comment]
Делаешь плохие коммиты!
Если поправил 2 программы, то делай 2 разных коммита

**Comment by antosha417** [comment]
### Почему такой странный цикл?

```python 
    line_coords_list = [[[50, 400], [300, 400]],
                        [[100, 450], [150, 450]],
                        [[300, 300], [400, 300]],
                        [[10, 350], [210, 350]],
                        [[10, 300], [110, 300]],
                        [[200, 450], [400, 450]],
                        [[300, 425], [425, 425]],
                        [[200, 375], [450, 375]]]

    for number in range(len(line_coords_list)):

        a = line_coords_list[number - 1]
        x = a[0]
        y = a[1]
        wave = gr.Line(gr.Point(x[0], x[1]), gr.Point(y[0], y[1]))
        wave.setOutline('white')
        wave.draw(window)
```

### Нужно писать что-то вроде
```python
lines_coords = [[[50, 400], [300, 400]],
                        [[100, 450], [150, 450]],
                        [[300, 300], [400, 300]],
                        [[10, 350], [210, 350]],
                        [[10, 300], [110, 300]],
                        [[200, 450], [400, 450]],
                        [[300, 425], [425, 425]],
                        [[200, 375], [450, 375]]]
for begin, end in lines_coords:
    wave = gr.Line(gr.Point(*begin), gr.Point(*end))
    ...
```

**Comment by antosha417** [comment]
Пока ставлю тебе 0,8  за задачу, чтобы поднять поправь код.

**Comment by MaKYaro** [comment]
@antosha417, переделал циклы 8862c8af5bd8ad047fcd404bd11e7890f10963f7

**Comment by antosha417** [comment]
Хорошо.

Вместо вот этого: 
```python 
x = coord[0]
y = coord[1]
```
Можно писать так:
```python
x, y = coord
```
Это называется распаковка. То есть если знаешь, что там только 2 значения, то можно одной строчкой их распаковать.

Закрывай issue. Ставлю оценку
